#!/bin/bash

# wait for jira lock file to disappear
while [ -f ${JIRA_HOME}/.jira-home.lock ]
do
  sleep 1
  echo "${JIRA_HOME}/.jira-home.lock is present ..."
  echo waiting for other node to terminate
done

# update server.xml
cat conf/server.xml.orig > conf/server.xml

if [ ${CATALINA_CONNECTOR_PROXYNAME} ]
then
  #xmlstarlet ed --insert Server/Service/Connector[@port=8080] --type attr -n proxyName -v ${CATALINA_CONNECTOR_PROXYNAME:-} conf/server.xml > conf/server.xml
  xmlstarlet ed --inplace --insert Server/Service/Connector[@port=8080] --type attr -n proxyName -v ${CATALINA_CONNECTOR_PROXYNAME:-} conf/server.xml
fi

if [ ${CATALINA_CONNECTOR_PROXYPORT} ]
then
  #xmlstarlet ed   --insert Server/Service/Connector[@port=8080] --type attr -n proxyPort -v ${CATALINA_CONNECTOR_PROXYPORT:-} conf/server.xml > conf/server.xml
  xmlstarlet ed --inplace --insert Server/Service/Connector[@port=8080] --type attr -n proxyPort -v ${CATALINA_CONNECTOR_PROXYPORT:-} conf/server.xml
fi

if [ ${CATALINA_CONNECTOR_SCHEME} ]
then
  #xmlstarlet ed   --insert Server/Service/Connector[@port=8080] --type attr -n scheme -v ${CATALINA_CONNECTOR_SCHEME:-} conf/server.xml > conf/server.xml
  xmlstarlet ed --inplace --insert Server/Service/Connector[@port=8080] --type attr -n scheme -v ${CATALINA_CONNECTOR_SCHEME:-} conf/server.xml
fi





JAVA_HOME=/opt/java/
export JAVA_HOME
#yes
./bin/catalina.sh run
